### ISSUE TITLE
Open API를 이용하여 데이터를 가져오기

### ISSUE THREAD

**Issue by Hyung1Jung** [thenaun-workspace/covid-19-info#3]
공공데이터 Open API를 이용하여 raw 데이터를 가져오기

- open API 활용을 위해 서비스 인증 키 url에 RestTemplate Method를 이용하여 요청을 보낸 후 String.class로 매핑을 받아 반환한 후 커스터마이징하여 raw 데이터를 받아온다.
- 데이터를 가져오는 것만 해볼 것이기 때문에  query string 방식으로 get 요청만 사용하고, 특정 리소스를 가져온다.
  ex) ?page=1&numOfRows=2&startCreateDt=20200101&endCreateDt=20201231
 

[데이터 가져올 때, RestTrmplate를 쓰는 이유에 관해 간단한 설명]

Open API의 데이터를 JSON 형식으로 받아오려고 한다.

RestTemplate이 없었다면 데이터를 변환할 때,  JSON 라이브러리를 사용해서 변환해야 한다.
JSON 라이브러리를 사용하면 코드의 길이가 늘어나고, 가독성, 유지보수 하는데 있어서 효율이 떨어진다.

하지만 RestTemplate를 이용하면 위에 관한 문제점을 해결할 수 있다.
RestTemplate은 스프링 3.0부터 지원하고 http 통신에 유용하게 쓸 수 있는 템플릿이며, HTTP 서버와의 통신을 단순화하고 RESTful 원칙을 지킨다.
또, http 통신시  응답의 타입에 따라 별도의 로직이 필요한 HttpClient의 문제점을 해결할 수 있다.

구현을 기반으로 블로그에  이것에 관한 '생각, 자료 조사 및 정보' 포스팅 완전히 마무리 되면 링크와 함께 이슈로 등록할 예정

**Comment by thenaun-woody** [comment]
위의 작성해주신 내용은 질문거리가 한 두개가 아닐거같은데, 포스팅이 완성이 되면 링크를 달아주세요. 그때 관련내용과 왜 이걸 썼는지에 대한 이유에 대해서 논의해보면 될 것 같네요.

`RestTemplate`을 사용했을 때 기본적으로 http connection 관리가 어떻게 되는지에 대한 내용을 정리를 해주셨으면 해요. 그리고 기본적으로 사용되는 (스프링이 제공해주는) httprequestfactory가 어떤 문제가 있을지, 그것을 해결하기 위해서는 어떤식으로 customize를 할 수 있을 지에 대해서 고려를 하시면 될 것으로 보입니다.

📍keyword
http connection, ClientHttpRequestFactory

**Comment by Hyung1Jung** [comment]
네! 말씀해주신 http connection, ClientHttpRequestFactory에 관해 고려해보면서 구현하도록 하곘습니다.

**Comment by Hyung1Jung** [comment]
데이터만 받아오는 것을 feature2로 두고 머지 후
HttpComponentsClientHttpRequestFactory 관련 customize을 feature3으로 했을까 싶네요..
또, HttpComponentsClientHttpRequestFactory 관련 customize을 config 패키지를 하나 만들어 refactoring하려고 생각중입니다!
